### ISSUE TITLE
WF1 Modifications for the Iraq Pilot

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#1]
## Background, context, and business value
Read the [README](https://github.com/OpenFn/openfn-lime-pilot?tab=readme-ov-file#prototype-design) from the original prototype implementation to refresh your memory on `Workflow 1`. Also see [this video](https://www.loom.com/share/cc85751b93754e08a95119b9949463ee) for a walk through. 

## The specific request, in as few words as possible
For the Iraq pilot implementation, we want to modify the [wf1 jobs](https://github.com/OpenFn/openfn-lime-pilot/tree/main/workflows) to update and extend the mappings. 

**See diagram [workflow - TECHNICAL](https://lucid.app/lucidchart/6b000d68-3e60-45e1-82bb-8f1d57d683db/edit?invitationId=inv_d2810b32-4070-4e9a-9f19-6496d9c9bb32&page=Sd-0A22pdvy4#) for updated specs.** 

### wf1-1-getTEIs (dhis2)
Then see [this diagram](https://lucid.app/lucidchart/6b000d68-3e60-45e1-82bb-8f1d57d683db/edit?invitationId=inv_d2810b32-4070-4e9a-9f19-6496d9c9bb32&page=Sd-0A22pdvy4#) for updated query parameters: 
```
program: ‘w9MSPn5oSqp’ , 
orgUnit: ‘OPjuJMZFLop’, 
programStatus: 'ACTIVE'
```

### wf1-2-getLocations (dhis2) --> *new* step
Add a _new_ workflow step to GET `/api/optionGroups/kdef7pUey9f?fields=id,displayName,options[id,displayName,code]` in order to return a list of `place of living` locations, that you will need to map OMRS `address` in the next step. The response will look [like this payload](https://github.com/OpenFn/openfn-lime-pilot/blob/main/sample-data/pilot/dhis2_placeOfLiving_optionGroup_%20kdef7pUey9f.json). 

We'll use this^ response to _dynamically_ generate a mapping table (that might look like something like this if we wanted to hardcode this table). 
<img width="1090" alt="Screenshot 2024-09-02 at 4 29 10 PM" src="https://github.com/user-attachments/assets/f5ef548c-92b6-424f-820b-d2c91269d1a1">

### wf1-2-createPatients (omrs) --> *rename to wf1-3*
Before you map Patient data, you will need to send a POST request to `'idgen/identifiersource/8549f706-7e85-4c1d-9424-217d50a2988b/identifier'` to generate a unique identifier for each payload. (This step should be the same as the prototype.)

Then we should update and add field mappings according to [this WF1 mapping spec](https://docs.google.com/spreadsheets/d/1wQDnMMejdGM2L7xhVpDo_52LbZQRBnYLz4maTGS-3U4/edit?gid=1480974404#gid=1480974404). 
- see [rows 8-9 in mapping spec](https://docs.google.com/spreadsheets/d/1wQDnMMejdGM2L7xhVpDo_52LbZQRBnYLz4maTGS-3U4/edit?gid=1480974404#gid=1480974404) for how to map the location options from the prior step

[See payload](https://github.com/OpenFn/openfn-lime-pilot/blob/main/sample-data/pilot/openmrs_postPatientBody.json) for an example request body that looks similar to what you need to send to OpenMRS when you create Patients (POST '/patient').  

### wf1-3-updateTEIs (dhis2) --> *rename to wf1-4*
[See diagram](https://lucid.app/lucidchart/6b000d68-3e60-45e1-82bb-8f1d57d683db/edit?invitationId=inv_d2810b32-4070-4e9a-9f19-6496d9c9bb32&page=Sd-0A22pdvy4#) or below sample code for how the mappings in this step should be updated. 

```
program: w9MSPn5oSqp, 
orgUnit: OPjuJMZFLop, 
attributes: [
  {attribute: "P4wdYGkldeG", value: ${patient_number}, //DHIS2 patient number to use as lookup key
   {attribute: "AYbfTPYMNJH", value: ${patient.uuid}, //OMRS patient uuid   
   {attribute: "ZBoxuExmxcZ", value: ${patient.identifier[0].identifier}} //id generated in wf1-2 e.g., "IQ146-24-000-027"
]
```

## API Documentation 
- DHIS2 latest docs: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-239/metadata.html
- OMRS REST API docs: https://rest.openmrs.org/#openmrs-rest-api

### Credentials
- DHIS2: See LP `MSF DHIS2 UAT - June 2024`
- OpenMRS: See LP `MSF OpenMRS Demo`

### Data
Run `wf-1-1` to get TEIs from DHIS2

## Output
If DHIS2 returns X patients, then X number of patients should be created in OpenMRS. See example output payload: https://github.com/OpenFn/openfn-lime-pilot/blob/main/sample-data/pilot/openmrs_postPatientBody.json

## Toggl 
`MSF 2024`

**Comment by aleksa-krolls** [comment]
@mtuchi this is the first MSF issue ready for devpt today - more to come tomorrow. Ping me on Slack if any questions or if helpful to talk through this.

**Comment by aleksa-krolls** [comment]
@mtuchi I added links to API documentation above. For querying `/optionGroups` from dhis2, fyi this is leveraging the Metadata API, which doesn't have a ton of docs specific to `optionGroups`, but generally describes how to interact with and filter this API. But fyi I have tested the http GET request I want to send on postman to verify it returns the data we need. 
https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-239/metadata.html?h=optiongroup+develop+2.39#webapi_browsing_the_web_api

**Comment by mtuchi** [comment]
I will pick this up on Monday

**Comment by aleksa-krolls** [comment]
hey @mtuchi as discussed
1. I updated the [mapping spec](https://docs.google.com/spreadsheets/d/1wQDnMMejdGM2L7xhVpDo_52LbZQRBnYLz4maTGS-3U4/edit?gid=1480974404#gid=1480974404) with the FULL json paths (e.g., `person.gender`)
2. See [this payload](https://github.com/OpenFn/openfn-lime-pilot/blob/main/sample-data/pilot/openmrs_postPatientBody.json) for an example output to send to OMRS

**Comment by mtuchi** [comment]
**EOD Update**

I have manage to update the mapping for create patients but two fields are not mapped yey(commented out) [`countryDistrict and cityVillage`].  I have also add mapping for `locations`, `statusMap` and `nationalityMap` in the get-locations step. 

@aleksa-krolls you can proceed with testing on https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/94e04fb5-d5ae-45ad-be31-98b902f36861?v=9

There are couple of improvements on adaptors that i have i noticed when i was working on this issue, i will open a PR on adaptors for those changes

**Comment by aleksa-krolls** [comment]
hey @mtuchi  some WF1  feedback...
1. Something is off with the filtering by cursor in WF1. [See run](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/94e04fb5-d5ae-45ad-be31-98b902f36861?a=a3659d51-0489-41c7-bc0a-84e6d24055c1&m=expand&s=be724c80-92c8-4fa9-8c3a-d28c5a298fd5&v=32#log) where  my input is `{ "manualCursor": "2019-09-13T08:00:00.00" }` and yet `# of TEIs to migrate to OMRS (after filtering)` is ZERO! I expect at least the TEI `eWXRNHtmHB0` to be returned because its `lastUpdated` is AFTER my cursor (`2024-09-13T11:17:48.386`).
```
{
    "created": "2019-06-13T10:43:47.558",
    "orgUnit": "OPjuJMZFLop",
    "trackedEntityInstance": "eWXRNHtmHB0",
    "trackedEntityType": "cHlzCA2MuEF",
     "lastUpdated": "2024-09-13T11:17:48.386",
```
2. I'm noticing the workflow executes all steps, even if NO teis found to sync to OMRS. [See example run](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/runs/8af55c16-1c21-4b17-9353-6b4e640f4ca9) with input cursor `{ "manualCursor": "2019-09-12T00:00:00.00" }`. Can you pls update the edge conditions accordingly? Feel free to test and implement on app with this input and then sync to GH, if easier. 
2.

**Comment by mtuchi** [comment]
I have update the teis to use `updatedAt` instead of `lastUpdatedAt` which doesn't exist. I have also add edge condition
