### ISSUE TITLE
WF2-2-upsertTEIs add mappings

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#10]
## Background, context, and business value
Ref #2 for the workflow 2 original specs. 

## The specific request, in as few words as possible
I need your help adding mappings for the step `wf2-2-upsertTEIs`. **See [mapping - upsertTEIs](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=1220746320#gid=1220746320)** for the specs. Note that I've drafted some of these mappings already but need your help with the rest. 

See `workflow 2` diagram in the LucidChart [workflow - TECHNICAL](https://lucid.app/lucidchart/6b000d68-3e60-45e1-82bb-8f1d57d683db/edit?invitationId=inv_d2810b32-4070-4e9a-9f19-6496d9c9bb32&page=Sd-0A22pdvy4#) for reference.

### wf2-2-upsertTEIs.js (dhis2)
Note that you will need to add 3 mapping tables (nationality, status, placeOfLiving) to implement these new field mappings. 

## API Documentation 
- DHIS2 latest docs: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-239/metadata.html
- OMRS REST API docs: https://rest.openmrs.org/#openmrs-rest-api

### Credentials
- DHIS2: See LP `MSF DHIS2 UAT - June 2024`
- OpenMRS: See LP `MSF OpenMRS Demo`

### Data
Run `wf-2-1` to get patients from OMRS

## Output
If OMRS returns X patients, then X number of patients should be upserted in DHIS2. 
For each Patient, we will query for Encounters. If Z Encounters are returned, then Z Events should be created in DHIS2. 

## Toggl 
`MSF 2024`

**Comment by mtuchi** [comment]
I have manage to fix the errors, were caused by wrong mappings, Now i am left with only one error 
```json
{
   "object": "Attribute.value",
   "value": "Value 'permanent_employee' is not a valid option for attribute v7k4OcXrWR8 and option set RpW3aZrlHDi"
}
```

**Comment by aleksa-krolls** [comment]
hey @mtuchi the value should actually be `fixed_employee`. I've updated the [mapping specs](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=1533228941#gid=1533228941) accordingly

**Comment by aleksa-krolls** [comment]
hey @mtuchi I've merged all your PRs to staging, but WF2 is now failing at step `5-get-teis` - [see run](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/runs/2a66d70b-20a6-4b7d-b3d5-56e8dc9875e5) where my initial input cursor is `{ "lastRunDateTime": "2024-09-13T00:16:24.544Z"}` and returns error: 
```
{
  "message": "TypeError: Cannot read properties of null (reading 'patient')",
  "name": "RuntimeError",
  "severity": "fail",
  "source": "runtime",
  "subtype": "TypeError"
}

```

**Comment by aleksa-krolls** [comment]
@mtuchi can we move this to Review? Or were you still working on something here?
