### ISSUE TITLE
wf2 - Change Encounters query and add logic for multiple forms

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#12]
## Background, context, and business value
Ref #2 for the original WF2 specs. 

Currently wf2 step `3-get-encounters` looks like this where we're only returning 1 Encounter. We need to modify this logic to handle multiple Encounters and multiple Forms.
```
getEncounters({
  q: 'Aisha',
  v: 'full',
  limit: 1,
  encounterType: '95d68645-1b72-4290-be0b-ec1fb64bc067',
});
```
FYI - every time a new `form` is submitted in OMRS --> a new `encounter` is created. This is why your encounters payloads look like this...
```
{
            "uuid": "35f833cf-abe5-4f31-a08a-47f624a31521", //encounter uuid
            "display": "Consultation 09/11/2024",
            "encounterDatetime": "2024-09-11T06:29:57.000+0000",
            "patient": {
                "uuid": "7c759307-6231-4f72-be48-3d48eb439de0",
                "display": "IQ146-24-000-048 - Aisha MHtwo",
            },
            "form": {
                "uuid": "82db23a1-4eb1-3f3c-bb65-b7ebfe95b19b", 
                "display": "MSF Mental Health - mhGAP Baseline", //form that created this encounter
 ```
 In OMRS, there will be multiple forms (and therefore multiple encounters) we need to map to DHIS2 events. And remember `1 encounter = 1 event`. [See OMRS forms list](https://docs.google.com/spreadsheets/d/1QPMwzXmssWg8qtrwxoEpjhms5jYTRzVnOkeOSRzpVn4/edit?gid=1565116219#gid=1565116219). 
 

## The specific request, in as few words as possible
**[Watch this video](https://www.loom.com/share/033093994ed047b59e37765b5a41b221) for more context on the changes we need to make.**

## 3-get-encoutners
1. Modify the query as follows and run the workflow with a cursor date `2024-09-01`... this should return 9 encounters for patient `Aisha MHtwo`. 
```
getEncounters({ q: 'MHtwo', v: 'full' );
```
2. Group the encounters by `form.uuid` where `uuid` is in this list `['82db23a1-4eb1-3f3c-bb65-b7ebfe95b19b', '6a3e1e0e-dd13-3465-b8f5-ee2d42691fe5']. (Note that right now we're only mapping 2 forms, but there will be 6 later on!)
<img width="1021" alt="Screenshot 2024-09-11 at 9 45 26 AM" src="https://github.com/user-attachments/assets/e6c13463-ac5d-455d-89c4-b6287eb99b76">

Your output should be 1 encounter for each `form.uuid` we want.
- Form.uuid `82db23a1-4eb1-3f3c-bb65-b7ebfe95b19b` --> should return only `1` encounter
- Form.uuid `6a3e1e0e-dd13-3465-b8f5-ee2d42691fe5` --> this will return `2` encounters at first. (This is bad test data, so please only keep the first `e.g., encounter.slice(0,1)` returned for each form. We expect that there should only be 1 form filled out for each form type... so we should only sync the first one found.)

NOTE: There will be other encounters belonging to other form uuids. Discard these encounters --> we only want to hold onto the encounters for the forms in our list. 

## 4-get-options-map
We still get the same gist - no changes to this step. 

But now we need to ADD mappings for the new form - **see [mhGAP mapping spec](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=891114001#gid=891114001).** Note this mapping logic is the SAME as before. 
```
state.mhgapMap = {
    f6FhkzfZ5j3: '4dae5b12-070f-4153-b1ca-fbec906106e1', //Admission type
    R3g94vJ2yFR: '22809b19-54ca-4d88-8d26-9577637c184e', //Clinical diagnosis
    }
```

## 6-create-events
Now that we're mapping 2 forms/encoutners, we need to insert 2 different types of events. (And remember, eventually there will be up to 6 types of forms/events.). Each event type will have (1) its own `programStage` and (2) different mappings for `dataValues` (bc each event has a different set of questions). 

1. `MHPSS` events (the original form mapping) will look like this
```
{
      program: 'w9MSPn5oSqp',
      orgUnit: 'OPjuJMZFLop',
      programStage: 'MdTtRixaC1B', //mhpss baseline*
      trackedEntityInstance: TEIs[data.patient.uuid],
      eventDate: encounterDate,
      dataValues //mapped using state.mhpssMap(
 }
 ```
 2. `mhGAP` events (for the new form) will look like this
 ```
{
      program: 'w9MSPn5oSqp', //same
      orgUnit: 'OPjuJMZFLop', //same
      programStage: 'EZJ9FsNau7Q', //mhgap baseline*
      trackedEntityInstance: TEIs[data.patient.uuid],
      eventDate: encounterDate,
      dataValues //mapped using state.mhgapMap*
 }
 ```

## API Documentation 
- DHIS2 latest docs: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-239/metadata.html
- OMRS REST API docs: https://rest.openmrs.org/#openmrs-rest-api

### Credentials
- DHIS2: See LP `MSF DHIS2 UAT - June 2024`
- OpenMRS: See LP `MSF OpenMRS Demo`

### Data
Run `wf2-3-get-encounters` to get encounter for `Aisha MHtwo` from OMRS and run with cursor `2024-09-01`

## Output
If OMRS returns X patients, then X number of patients should be upserted in DHIS2. 
For each Patient, we will query for Encounters *and then filter by `form.uuid`*. If Z Encounters are returned, then Z Events should be created in DHIS2. 

### Testing guidance
For patient `Aisha MHtwo`...
- We will originally get `9` encounters --> once filtered by form.uuid, this should output `2` encounters (1 for `mhpss` form and 1 form `mhgap). 
- This means we will upsert 1 TEI in dhis2, and 2 events.

## Toggl 
`MSF 2024`

**Comment by aleksa-krolls** [comment]
hey @mtuchi btw when you get to this one, I recorded a quick [video walkthrough](https://www.loom.com/share/033093994ed047b59e37765b5a41b221) explaining how OMRS forms/encounters map to dhis2 events for more context.

**Comment by mtuchi** [comment]
@aleksa-krolls  I have manage to map the mhpss and mhgap form and create event for those two. See work in progress here #15

**Comment by mtuchi** [comment]
I have updated the mapping for employment status, The workflow is ready for testing now. 
@aleksa-krolls let me know when your ready to test so that i can update the workflow on app accordingly
