### ISSUE TITLE
WF2 modifications for the pilot

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#2]
## Background, context, and business value
Read the [README](https://github.com/OpenFn/openfn-lime-pilot?tab=readme-ov-file#prototype-design) from the original prototype implementation to refresh your memory on `Workflow 2`. Also see [this video](https://www.loom.com/share/e414eda7772d4f149d05ddba8ec0fa20) for a walk through.

## The specific request, in as few words as possible
For the Iraq pilot implementation, we want to modify the [wf2 jobs](https://github.com/OpenFn/openfn-lime-pilot/tree/main/workflows) to update and extend the mappings. 

**See `workflow 2` diagram in the LucidChart [workflow - TECHNICAL](https://lucid.app/lucidchart/6b000d68-3e60-45e1-82bb-8f1d57d683db/edit?invitationId=inv_d2810b32-4070-4e9a-9f19-6496d9c9bb32&page=Sd-0A22pdvy4#) for updated specs.** 

###  wf2-1-getPatients.js (omrs)
Change the query parameter on [L16](https://github.com/OpenFn/openfn-lime-pilot/blob/main/workflows/wf2/1-get-patients.js#L16) as follows... (note that we will update this later, but this will help get the right test data).
`searchPatient({ q: 'Aisha',  v: 'full', limit: '100' });` 

Then it looks like we were limiting by `100` records for performance reasons. Are we handling for paging already? If not we should implement that and assume this query _might_ return MORE than 100 records. Paging will look something like this...

```
"results":[ data...],
"links": [
        {
            "rel": "next",
            "uri": "{url}&limit=100&startIndex=100",
            "resourceAlias": null
        }
    ]
```

### wf2-2-upsertTEIs.js (dhis2)
No changes needed - I already updated some of the uids in [this job](https://github.com/OpenFn/openfn-lime-pilot/blob/main/workflows/wf2/2-upsert-teis.js). 

### wf2-3-getEncounters.js (omrs)
Similar to `wf2-1` step, (1) change the `q` query parameter, and (2) make sure handling for paging is implemented in case the query returns >100 encounters. _Also_ (3) add a query filter `&encounterType=95d68645-1b72-4290-be0b-ec1fb64bc067`. I think this will look like....

`getEncounters({ q: 'Aisha', v: 'full', limit: 100, encounterType: '95d68645-1b72-4290-be0b-ec1fb64bc067' });`

Your output should look similar [to this payload](https://github.com/OpenFn/openfn-lime-pilot/blob/main/sample-data/pilot/omrs_getEncounters_aishamhtwo.json).

Paging will look like this

```
"results":[ data...],
"links": [
        {
            "rel": "next",
            "uri": "http://msf-ocg-openmrs3-dev.westeurope.cloudapp.azure.com/openmrs/ws/rest/v1/encounter?patient=f642ceac-d612-4269-9534-339a08865ca3&v=full&limit=2&startIndex=2",
            "resourceAlias": null
        }
    ]
```

### wf2-4-getOclMap.js --> rename to wf2-4-getOptionsMap.js (http)

We're not using ocl in this implementation, so instead send an http GET request to fetch this json object of mappings: 
https://gist.github.com/aleksa-krolls/b22987f7569bc069e963973401832349

This will be used to translate option mappings in the next step. OMRS will give us a `value.uuid - External ID` as an _input_, and we'll use this gist to find the matching _output_ `DHIS2 Option UID`. 
```
{
    "value.display - Answers": "Psychologist",
    "value.uuid - External ID": "278401ee-3d6f-4c65-9455-f1c16d0a7a98",  //input from omrs
    "DHIS2 Option UID": "gLrTwy3IQX5",  //output for dhis2
    "OptionSet name": "Consultation done by - MHPSS baseline"
  },
  ```

### wf2-5-createEvents.js (dhis2)
The big changes:
1. Please change `programStage` to `MdTtRixaC1B`.
2. The [create events](https://github.com/OpenFn/openfn-lime-pilot/blob/main/jobs/wf2-5-createEvents.js#L125) operation needs to be able to append `dataElementIdScheme=UID` as a parameter. 
We want the job to send a request like `POST /api/events?dataElementIdScheme=UID`
(This query parameter tells DHIS2 that the value in dataValues is specified using the unique ID (UID) of the options.)
3. There will be 88 items in the event's dataValue array to map bc there will be 1 `dataValue` item for each `dataElement` (see col B) or row [in mapping spec](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=668564008#gid=668564008)
4. THEN we should update ALL mapping logic according to [this WF2 mapping spec](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=668564008#gid=668564008). Use the `OMRS JSON Path` (Col J) to find the source observation `obs[x]` to map to the destination `DHIS dataElement UID` (col B). 

Note that there are 3 main types of mappings: 
1. Direct mappings (1-1) where no translation is needed (you will see `n/a` in the transformation column)
2. Boolean mappings where OMRS "yes" answers (with a specific uuid) will need to be converted to `true`, and "no" answers converted to `false`
3. Option mappings* where an OMRS uuid will need to be converted to a dhis2 option code based on the `OptionsMap` returned in step `wf2-4`

#### mapping example 
For an mapping example, look at the mapping rule [on row 24](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=668564008#gid=668564008&range=J24) where we need to map to the dhis2 element `WDY6MkQWyHb`...

(a) Let's say your input encounter payload looked like below. Per the mapping spec, we need to find the `obs` where `obs[x].concept.uuid=='"722dd83a-c1cf-48ad-ac99-45ac131ccc96"` --> this is our `Input` for this mapping. 

```
{
    "results": [
        {
            "uuid": "183278f8-1f6e-4750-b8e5-a696f8c7dcfd",
            "display": "Mental Health 09/03/2024",
            "encounterDatetime": "2024-09-03T10:50:04.000+0000",
            "obs": [
                {
                    "uuid": "99011780-3c59-4098-8bff-7a7088094a86",
                    "display": "Provider type: Psychologist",
                    "concept": {
                        "uuid": "722dd83a-c1cf-48ad-ac99-45ac131ccc96",
                        "display": "Provider type",
                        "links": [
                            {
                                "rel": "self",
                                "uri": "http://msf-ocg-openmrs3-dev.westeurope.cloudapp.azure.com/openmrs/ws/rest/v1/concept/722dd83a-c1cf-48ad-ac99-45ac131ccc96",
                                "resourceAlias": "concept"
                            }
                        ]
                    },
                    "value": {
                        "uuid": "278401ee-3d6f-4c65-9455-f1c16d0a7a98",
                        "display": "Psychologist"
                    }
                }
            ]
        }
    ]
}
```
b) Then for this `obs[x]` we will find the `obs[x].value.uuid` to translate. For this example, that's `"value": {"uuid": "278401ee-3d6f-4c65-9455-f1c16d0a7a98"` ---> should be outputted as `gLrTwy3IQX5` (for psychologist). 

See [L154-155](https://gist.github.com/aleksa-krolls/b22987f7569bc069e963973401832349#file-msf_mhbaseline_optionsmap-json-L152-L157) for how we should use the gist `optionMap` to do this translation _from_ `value.uuid - External ID` --> `DHIS2 Option UID`
```
{
    "value.display - Answers": "Psychologist",
    "value.uuid - External ID": "278401ee-3d6f-4c65-9455-f1c16d0a7a98", //input from OMRS
    "DHIS2 Option UID": "gLrTwy3IQX5", //output for dhis2
    "OptionSet name": "Consultation done by - MHPSS baseline"
  },
  ```
(c) finally, this means that your event output sent to dhis2 will look something like this...
  ```
  {
      program: 'uGHvY5HFoLG',
      orgUnit: 'l22DQq4iV3G',
      programStage: 'hfKSeo6nZK0',
      trackedEntityInstance: TEIs[data.patient.uuid],
      eventDate: encounterDate,
      dataValues: [
        {
          dataElement: 'WDY6MkQWyHb', //column B from mapping spec = "Q: Consulted by?"
          value: "gLrTwy3IQX5", //matching Option UID from gist = A: "psychologist"
        },
```

## API Documentation 
- DHIS2 latest docs: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-239/metadata.html
- OMRS REST API docs: https://rest.openmrs.org/#openmrs-rest-api

### Credentials
- DHIS2: See LP `MSF DHIS2 UAT - June 2024`
- OpenMRS: See LP `MSF OpenMRS Demo`

### Data
Run `wf-2-1` to get patients from OMRS

## Output
If OMRS returns X patients, then X number of patients should be upserted in DHIS2. 
For each Patient, we will query for Encounters. If Z Encounters are returned, then Z Events should be created in DHIS2. 

## Toggl 
`MSF 2024`

**Comment by aleksa-krolls** [comment]
hey @mtuchi this is also ready to pick up. The mapping logic is a bit tricky to understand at first, so lmk if you want to talk through it... but once you get the hang of it, I think things will move quickly.

**Comment by mtuchi** [comment]
**EOD Update**

I have manage to work on the first two jobs in wf2, Everything is working as expected. 
I will pick this up tomorrow starting with paging on the first job

**Comment by mtuchi** [comment]
@aleksa-krolls can you remove the `{` and `}` at the start and the end of this raw json https://gist.github.com/aleksa-krolls/b22987f7569bc069e963973401832349

**Comment by mtuchi** [comment]
Made good progress, will finish up tomorrow

**Comment by aleksa-krolls** [comment]
hey @mtuchi 
1. FYI I merged a handful of mapping edits to `staging` branch following my testing last night. Please pull for the latest.
2. One feedback I need help with that isn't quite right. You had this transformation implemented... I've commented it out because there are 2 DHIS2 questions that use this OMRS concept as an input source. This resulted in ALL answers outputting as `TRUE`, when only one should.
https://github.com/OpenFn/openfn-lime-pilot/blob/0daa51c4ec66ca01b244d7014ff90e4770f2b021/workflows/wf2/6-create-events.js#L22-L29

See 2 DHIS2 dataElements that both rely on the same source OMRS concept uuid `722dd83a-c1cf-48ad-ac99-45ac131ccc96`. I've filtered the [MHPSS mapping spec](https://docs.google.com/spreadsheets/d/1ygYzwRxx3JBjF-WIzHKpz8DlWVRS3kw5uIYPa0ynpPk/edit?gid=668564008#gid=668564008). 
https://github.com/OpenFn/openfn-lime-pilot/blob/c17af352de3dfc84db65c85cbffd26233c1f43da/workflows/wf2/4-get-options-map.js#L53-L54
- This first mapping for `WDY6MkQWyHb` (`Q: Consultation done by`) is good and will return values like `psychologist`
- This second mapping for `pN4iQH4AEzk` (`Q: Diagnosis done by pyschologist?`) needs a special transformation because if the above mapping returns `psychologist`, then only should we return `pN4iQH4AEzk == TRUE`. Otherwise return FALSE or undefined.

**Comment by mtuchi** [comment]
I have address the comment above on this PR #13
