### ISSUE TITLE
wf2 - add mapping for consultation date

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#20]
Ref #2 for background and credentials. 

Some mapping feedback to implement: 
1. For each form I want to map `encounterDate` to "Consultation date" (which has a different dataElement Id in each form). I drafted the [mappings here](https://github.com/OpenFn/openfn-lime-pilot/blob/staging/workflows/wf2/4-get-options-map.js#L16) - can you pls figure out how to implement? 
```
CXS4qAJH2qD 
7phgLmRWQq
yUT7HyjWurN
```

2. More TBD

**Comment by mtuchi** [comment]
**EOD Update**
I have manage to add mapping for the consultation date for all three forms. See #33
