### ISSUE TITLE
wf2 failing - "TypeError: fn is not a function",

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#22]
## Describe the bug and expected behavior 
The client is still unable to test WF2 on `staging`. It is now failing on `Upsert TEIs` step. It seems to successful upsert some TEIs fine... but then fails on others. 
```
Sending get request to https://dhis2-uat.ocg.msf.org/api/trackedEntityInstances
ADA  with params: {"filter":["AYbfTPYMNJH:Eq:841852d1-86de-4716-b01d-a9caed916d48"],"ou":"OPjuJMZFLop","program":"w9MSPn5oSqp"}
ADA Retrieved trackedEntityInstances
JOB 841852d1-86de-4716-b01d-a9caed916d48 patient uuid
JOB mapped dhis2 payloads::  {
  "query": {
    "ou": "OPjuJMZFLop",
    "program": "w9MSPn5oSqp",
    "filter": [
      "AYbfTPYMNJH:Eq:841852d1-86de-4716-b01d-a9caed916d48"
    ]
  },
  "data": {
    "program": "w9MSPn5oSqp",
    "orgUnit": "OPjuJMZFLop",
    "trackedEntityType": "cHlzCA2MuEF",
    "attributes": [
      {
        "attribute": "fa7uwpCKIwa",
        "value": "unknown"
      },
      {
        "attribute": "Jt9BhFZkvP2",
        "value": "unknown"
      },
      {
        "attribute": "P4wdYGkldeG",
        "value": "Omar5"
      },
      {
        "attribute": "ZBoxuExmxcZ",
        "value": "IQ146-24-000-302"
      },
      {
        "attribute": "AYbfTPYMNJH",
        "value": "841852d1-86de-4716-b01d-a9caed916d48"
      },
      {
        "attribute": "qptKDiv9uPl",
        "value": "male"
      },
      {
        "attribute": "Rv8WM2mTuS5",
        "value": 25
      },
      {
        "attribute": "WDp4nVor9Z7",
        "value": "1999-08-3"
      },
      {
        "attribute": "rBtrjV1Mqkz"
      },
      {
        "attribute": "Xvzc9e0JJmp",
        "value": "iraq"
      },
      {
        "attribute": "YUIQIA2ClN6",
        "value": "returnee"
      },
      {
        "attribute": "Qq6xQ2s6LO8"
      },
      {
        "attribute": "FpuGAOu6itZ",
        "value": "single"
      },
      {
        "attribute": "v7k4OcXrWR8",
        "value": "unemployed"
      },
      {
        "attribute": "SVoT2cVLd5O"
      }
    ]
  }
}
R/T Operation 3 complete in 6.421s
R/T Starting operation 4
R/T Removed configuration from final state
R/T Failed step Upsert TEIs after 13.264s
R/T {
  "message": "TypeError: fn is not a function",
  "name": "RuntimeError",
  "severity": "fail",
  "source": "runtime",
  "subtype": "TypeError"
}
```

## To Reproduce
 [See run failure](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/0f8ec062-1a2d-4f13-a8c5-b8298004512c?s=6973c510-b36d-4c42-82f5-b26d8cd36a57&v=99&m=expand&a=9a761d8d-1299-4b49-809b-69112c0e07cb#log) and feel free to re-run.

My initial input for wf2-1 was `{ "lastRunDateTime": "2024-09-16T00:00:00.000Z" }`. 

### expression.js
Ref #2 for credentials - WF2

Branch off of `staging`
https://github.com/OpenFn/openfn-lime-pilot/tree/main/workflows/wf2

## Toggl 
`MSF 2024`

**Comment by aleksa-krolls** [comment]
hey @mtuchi I added a bad console.log which solved for this first TypeError, but now getting this [new 500 dhis2 error](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/0f8ec062-1a2d-4f13-a8c5-b8298004512c?v=104&a=4ac72442-ba94-469d-94e1-38942754f987&m=expand&s=6973c510-b36d-4c42-82f5-b26d8cd36a57#log)... any idea what this means? 
```
Request failed with status code 500
ADA {
  "httpStatus": "Internal Server Error",
  "httpStatusCode": 500,
  "status": "ERROR",
  "message": "Transaction rolled back because it has been marked as rollback-only"
}

```

**Comment by mtuchi** [comment]
@aleksa-krolls i have investigated the 500 error it seems to be on DHIS2 side. But how ever when i retried the workflow it seems to be working now and i was getting a much better error. (400 Bad request) which seems to be cause by bad data on `WDp4nVor9Z7` mapping. The value was not properly formatted to `YYYY-MM-DD`. I have update the mapping and sync the changes back to GitHub, The workflow now is working as expected.
