### ISSUE TITLE
new workflow to auto-generate OptionsMap

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#32]
## Request
Then, every time the client updates the options map, I have to manually generate [this gist](https://gist.github.com/aleksa-krolls/2f309595110239cfcc8251017cf11592). To automate this process and save us time, can you please help me create a new workflow to auto-generate this OptionsMap? 

## Input
A csv file that I'll upload to GoogleSheets. It would be nice if in the job I could specify the name of the file I want to pull. 

Example file (you can assume the csv files will always have the same column names: 
https://drive.google.com/file/d/1OTXLjnFHhR4Nety9mRE_LbtC_r2ZD7w-/view?usp=drive_link

## Output
A json file that looks like this gist: https://gist.github.com/aleksa-krolls/2f309595110239cfcc8251017cf11592

Draft mapping: 
```
value.display - Answers: csv.Answers
value.uuid - External ID": csv.External ID
DHIS2 DE full name: DHIS2 DE full name
DHIS2 DE UID: csv.DHIS2 DE UID
OptionSet name: csv.OptionSet name
DHIS2 Option Set UID: csv.DHIS2 Option Set name
DHIS2 Option name: csv.DHIS2 Option name
DHIS2 Option UID: csv.DHIS2 Option UID
DHIS2 Option Code: csv.DHIS2 Option code
```

**Comment by mtuchi** [comment]
**Quick Feedback**
- The file in google drive must be a googlesheet file so that we can use googlesheet adaptor to fetch the values
- After we generate the mapping, what should we do with empt data that is being mapped. For example 
```json
  {
      "DHIS2 DE UID": "",
      "DHIS2 DE full name": "",
      "DHIS2 Option Code": "",
      "DHIS2 Option Set UID": "",
      "DHIS2 Option UID": "",
      "DHIS2 Option name": "",
      "OptionSet name": "Vulnerability criteria - The child is",
      "value.display - Answers": "Adopted",
      "value.uuid - External ID": ""
    },
 ```

**Comment by aleksa-krolls** [comment]
@mtuchi cool, then go ahead and convert to GoogleSheet --> and I'm okay with following the process in the future. 

And if `DHIS2 DE full name` OR `value.uuid - External ID` are not defined ( `""` or `NA` in the input)... then filter this out and do NOT include these rows in OptionMap.

**Comment by mtuchi** [comment]
@aleksa-krolls should the filter be `OR` or `AND` ?
Because if one of the value is `true` between `DHIS2 DE full name` and `value.uuid - External ID` is true then we will still have `"NA"` or `""` in the values that is `false`

Eg: `value.uuid - External ID` has a valid value but `DHIS2 DE full name` has invalid value 👇🏽 
```json
{
      "DHIS2 DE UID": "NA",
      "DHIS2 DE full name": "NA",
      "DHIS2 Option Code": "",
      "DHIS2 Option Set UID": "NA",
      "DHIS2 Option UID": "NA",
      "DHIS2 Option name": "NA",
      "OptionSet name": "Sex - All",
      "value.display - Answers": "Male",
      "value.uuid - External ID": "625baaf5-ba75-4c23-bdef-283fd47c34db"
    },
```

Eg: `DHIS2 DE full name` has valid value but `value.uuid - External ID` has invalid value
```json
  {
      "DHIS2 DE UID": "Xvzc9e0JJmp",
      "DHIS2 DE full name": "Nationality",
      "DHIS2 Option Code": "",
      "DHIS2 Option Set UID": "GL - Nationality",
      "DHIS2 Option UID": "CcpigvKey7O",
      "DHIS2 Option name": "China",
      "OptionSet name": "Country",
      "value.display - Answers": "China",
      "value.uuid - External ID": ""
    },
```

**Comment by aleksa-krolls** [comment]
@mtuchi pls also filter out rows if `"DHIS2 DE full name": "NA"` OR if `value.uuid - External ID": ""`

All of these should be OR scenarios... so only if `DHIS2 DE full name` and `value.uuid - External ID` have legit values (not empty strings or `NA`) should we include in the optionMap

**Comment by mtuchi** [comment]
@aleksa-krolls noted, I have update the workflow accordingly, [See output in this latest workflow run ](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/29376a74-d299-4066-9e78-271ca1777734?a=ead6b99d-cf25-4eb2-b489-3a6cfc90428d&m=expand&s=ba19bc93-8f07-480f-80df-ee3f0b0d27e0&v=26#output)
