### ISSUE TITLE
wf2 - get all encounters via FHIR API?

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#34]
## Background, context, and business value
Right now, in WF2 we...
1. get all Patients created/updated since last sync
2. for each Patient, get Encounters

However, we've learned that when Encounters are updated/created --> the related `Patient` record is _not_ updated. Therefore, if only Encounters are modified... this workflow will not fetch these records. The workflow only fetches records if the Patient AND Encounter records are modified. 

## Request
Can you pls assist with some API discovery and analysis? I think we can get _all_ Encounters modified in OMRS using the [FHIR REST API](https://openmrs.atlassian.net/wiki/spaces/projects/pages/26935684/FHIR+OpenMRS+Strategy+Tools+FHIR+API+and+Help)? 
- See more on FHIR apis: https://www.hl7.org/fhir/http.html

This request seems to return Encounters in bulk:  `/openmrs/ws/fhir2/R4/Encounter`
- Can you see if you can this seems to return all records or if we need to add paging? 
- Does it look possible to add a filter parameter (e.g., `meta.lastUpdated={cursor}` to the API request to only get newly updated Encounters? 
- Does this response look similar to the OMRS `/encounters` endpoint? Or should we consider using this only to get a list of IDs for encounters last updated... and then use the regular OMRS `/encounters` api (as is) to get the rest of the `obs` data? 

## Input
Same OMRS credentials as #2 

## Toggl 
`MSF 2024`

**Comment by aleksa-krolls** [comment]
@mtuchi see LucidChart and use cursor `2024-09-29`for testing
https://lucid.app/lucidchart/38ae80f0-0650-4fea-9a11-dc1e19f9bd4f/edit?view_items=d1UdCvJE-99m&invitationId=inv_7c1bdd58-2ffe-4d84-b6fa-b8738126262c

**Comment by mtuchi** [comment]
@aleksa-krolls i am curios for this cursor `2024-09-29` how many encounters are you expecting ?

**Comment by mtuchi** [comment]
@aleksa-krolls I manage to fetch all patients with updated encounters using `/ws/fhir2/R4/Encounter` endpoint, See #42  But It require adaptor changes that need joe's input, See work in progress here https://github.com/OpenFn/adaptors/pull/765

**Comment by aleksa-krolls** [comment]
@mtuchi great that it sounds like you figured something out here, but please walk me through the proposed approach before spending time on any adaptor work. (That costs extra time/money, so I want to make sure we're aligned on the way forward before going and have considered using generic `http` before doing a bunch of new adaptor work.) I'll book some time for tomorrow --> so feel free to pause work here until we chat, and move onto the next issue.

**Comment by mtuchi** [comment]
**API Discovery** 
- We can get `R4/Encounter` since `lastUpdated` using a query like this `_lastUpdated: 'ge2024-09-29'`.  
  - `_lastUpdated`: Filters resources based on the last time they were updated. You can use operators like `gt` (greater than), `lt` (less than), `ge` (greater than or equal to), and `le` (less than or equal to).
     - `gt2024-09-01T00:00:00Z` filters encounters updated after September 1, 2024.
     - `lt2024-10-01T00:00:00Z` filters encounters updated before October 1, 2024.

- We can use `resource.subject.reference` to extract the patient id. [See sample payload here](https://github.com/OpenFn/openfn-lime-pilot/blob/34-all-encounters/sample-data/r4-encounters.json)
-  Some encounter uuid returns `404`

**OpenMRS Discovery**

- API endpoint 
Currently all adaptor operation uses `/ws/rest/v1/` api path, So we can't make a get request to `/ws/fhir2/R4/Encounter` without modifying the adaptor code.
- API response
The API response for `/ws/fhir2/R4/Encounter` has a different structure which can not be auto page with the current implementation of request helper. I have created a request helper that will work for `ws/fhir2/R4/Encounter` in https://github.com/OpenFn/adaptors/pull/765

**Comment by aleksa-krolls** [comment]
hey @mtuchi last week we discussed that I want to move forward with this... anything else blocking you here? Or can I move to the top of backlog?

**Comment by mtuchi** [comment]
@aleksa-krolls Joe asked me to look into [OpenMRS Documentation](https://openmrs.atlassian.net/wiki/spaces/projects/pages/26935963/FHIR+Swagger+Documentation). Also he asked me if we have more time to design the adaptor function, [See his comment here](https://github.com/OpenFn/adaptors/pull/765#issuecomment-2394979988)

Unfortunately the Swagger documentation was not helpful. According to the instruction i should get the swagger documentation when accessing http://msf-ocg-openmrs3-dev.westeurope.cloudapp.azure.com/openmrs/module/fhir/rest/swagger.json,  but i am `404`

**Comment by aleksa-krolls** [comment]
hey @mtuchi let's please chat about this after standup tomorrow AM

**Comment by aleksa-krolls** [comment]
@mtuchi I also can't find the Swagger docs - doesn't look like they have this enabled in their deployment. I will need to ask the client. 

For now, I would only worry about a generic FHIR `GET` - we might get any of [these resource](https://fhir.openmrs.org/). Don't worry about POST, PUT, etc... we don't know enough yet about OMRS's fhir api, nor do we have budget to spend a lot of time on this. 
cc @josephjclark

**Comment by mtuchi** [comment]
**EOD Update**

I have update the function to `fhir.get()` and add unit test. Waiting for @josephjclark feedback

**Comment by mtuchi** [comment]
Hiya @josephjclark how do you feel about this implementation using http adaptor 👇🏽 ?

```js
cursor("2024-09-29");

get(
  "/ws/fhir2/R4/Encounter",
  { query: { _count: 10, _lastUpdated: `ge${$.cursor}` }, parseAs: "json" },
  (state) => {
    state.encounters = state.data;
    return state;
  }
);

fn((state) => {
  const { link, total } = state.data;
  const nextUrl = link.find((l) => l.relation === "next")?.url;

  if (nextUrl) {
    const queries = nextUrl.split("?")[1];
    const pairs = queries.split("&");
    const params = {};

    pairs.forEach((pair) => {
      const [key, value] = pair.split("=");
      params[decodeURIComponent(key)] = decodeURIComponent(value || "");
    });
    // Modify the total for the next get request to fetch all records 
    state.newQuery = { ...params, _count: total };
  }

  return state;
});

fnIf(
  $.newQuery,
  get(
    "/ws/fhir2/R4",
    { query: $.newQuery, parseAs: "json" },
    (state) => {
      delete state.encounters.link
      state.encounters.entry.push(...state.data.entry);
      console.log(state.encounters.entry.length)
      return state;
    }
  )
);
```

I know the work around for paging is not very nice but should get the job done. This will buy us time for a better implementation of OpenMRS FHIR

**Comment by josephjclark** [comment]
@mtuchi That looks fine to me, this sort of thing is exactly what http is for. Wasn't pagination part of the problem here?

Openmrs should how have the `fhir` functions in it so it's up to you which you want to use.

If you're not going to use the new fhir functions then we should probably raise a PR to remove them. We're sort of compounding bad decision on bad decision here...

**Comment by aleksa-krolls** [comment]
hey @mtuchi - Can you please help get [this PR](https://github.com/OpenFn/openfn-lime-pilot/pull/42) where we get ALL encounters (endpoint: `'/ws/fhir2/R4/Encounter'`) merged into `next-staging`?

**Comment by mtuchi** [comment]
Hiya @aleksa-krolls this is ready for QA, [See workflow run here](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/runs/41938e3f-4929-4cef-be3d-fedaa67bcfb2)

**Comment by aleksa-krolls** [comment]
hey @mtuchi  the [wf run](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/runs/41938e3f-4929-4cef-be3d-fedaa67bcfb2) you shared is failing on the `Create Events` step... can you please check it out in the AM? 

Once it's running again, then I've left you and @daissatou2 some testing next steps [on Slack](https://openfn.slack.com/archives/C017ELVRSM8/p1731000691791139). Aissatou can help create more test data if you need it. 

```
Failed step Create Events after 130ms
R/T {
  "message": "TypeError: Cannot destructure property 'trackedEntity' of 'state.TEIs[data.patient.uuid]' as it is undefined.",
  "name": "RuntimeError",
  "severity": "fail",
  "source": "runtime",
  "subtype": "TypeError"
}
```

**Comment by aleksa-krolls** [comment]
hey @mtuchi for errors [like this](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?a=ce78e3f9-47ba-4ead-b2be-305a3e91d9f9&m=expand&s=a1176a6e-cdee-4ddc-9fe1-e49aa7b719cd&v=30#log) where `Enrollment value is null`... this means something is wrong with our workflow and how we're enrolling TEIs in programs in earlier steps OR perhaps we're not correctly linking this Event to the TEI. **Is this still an issue or was it resolved on Friday?**

In our [old code](https://github.com/OpenFn/openfn-lime-pilot/blob/main/workflows/wf2/6-create-events.js#L50-L51), events were always linked to a `programStage` and a `trackedEntityInstance`. 

Error message from the run you shared: 
```
ADA Request failed with status code 409
ADA {
  "status": "ERROR",
  "validationReport": {
    "errorReports": [
      {
        "message": "Event: `BzJnRv50vZL`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "BzJnRv50vZL"
      },
      {
        "message": "Event: `TMHijMdql7R`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "TMHijMdql7R"
      },
      {
        "message": "Event: `vFljnPGSrYd`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "vFljnPGSrYd"
      },
      {
        "message": "Event: `LgfF6R8EPMw`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "LgfF6R8EPMw"
      }
    ]
  },
```
