### ISSUE TITLE
wf2/3-get-encounters fails with Type error

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#37]
## Describe the bug and expected behavior 
Fails with error `TypeError: Cannot read properties of undefined (reading 'flat')`. I think it's failing when 0 patient or 0 encounter records are returned...

## To Reproduce
1. [See run failure](https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/w/0f8ec062-1a2d-4f13-a8c5-b8298004512c?v=161&a=5fd7baa6-ca8f-4972-a296-3ff970c425ae&m=expand&s=8fb577e5-d068-4d47-8172-81f08153ced9#log)
2. To replicate, use this cursor: `{ "lastRunDateTime": "2024-09-30T12:00:00.000Z" }`

### expression.js
`3-get-encounters.js`
I was testing on `staging`... not sure if you want to branch off of that, or if we should first merge your other changes pending code review (bc Joe will be out for >1 week). Let's discuss. 

## Toggl 
`MSF 2024`

**Comment by mtuchi** [comment]
@aleksa-krolls i have update the edge conditions in this PR #39, When you merge make sure to re-run the workflow from beginning
