### ISSUE TITLE
Use new tracker API to update events

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/openfn-lime-pilot#45]
**Description**
In `6-create-events.js` step we can use the new tracker API to create or update events. It will require minor changes in the mapping and error handling logic

```js
create(
  'tracker',
  {
    events: state => {
      const events = state.encountersMapping.map(
        ({ eventDate, trackedEntityInstance, ...e }) => ({
          ...e,
          occurredAt: eventDate,
          trackedEntity: trackedEntityInstance,
        })
      );
      // console.log(events);
      return events;
    },
  },
  {
    params: {
      async: false,
      dataElementIdScheme: 'UID',
      importStrategy: 'CREATE_AND_UPDATE',
    },
  }
);
```

**Resources**
- [Events API](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-241/tracker.html#events)

**Comment by aleksa-krolls** [comment]
@mtuchi the above will _not_ work unless we are saving the event uid in OpenMRS... so we might need to do that. I will go think about how to achieve this and report back.

**Comment by mtuchi** [comment]
@aleksa-krolls i need a test example for this change, i don't know what to look at in DHIS2 if i run that code. I will look into this tomorrow

**Comment by aleksa-krolls** [comment]
Upsert events fails - [see run](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?s=a1176a6e-cdee-4ddc-9fe1-e49aa7b719cd&v=78&m=expand&a=5e6d14ea-d4af-4076-83dd-a83b9e8e79c6#log)... it doesn't look like this _updates_ events, and right now only creates. 

How to replicate? Run wf2 with the _same_ cursor multiple times. Make sure it's successful the first time, and then run it again to replicate this error. 

Errors: 
```
{
        "message": "ProgramStage: `EZJ9FsNau7Q`, is not repeatable and an event already exists.",
        "errorCode": "E1039",
        "trackerType": "EVENT",
        "uid": "SmdQabTUGeG"
      },
      {
        "message": "ProgramStage: `MdTtRixaC1B`, is not repeatable and an event already exists.",
        "errorCode": "E1039",
        "trackerType": "EVENT",
        "uid": "v0nzugLHUCw"
      },
      {
        "message": "ProgramStage: `MdTtRixaC1B`, is not repeatable and an event already exists.",
        "errorCode": "E1039",
        "trackerType": "EVENT",
        "uid": "rx1dUJhHFuv"
      }
```

**Comment by aleksa-krolls** [comment]
hey @mtuchi see below for the query to get `trackedEntities` _AND_ their related `events`. 
```
https://dhis2-uat.ocg.msf.org/api/tracker/trackedEntities?trackedEntity=NSffAYCgCvS&program=w9MSPn5oSqp&fields=*,enrollments[*],enrollments[events[*]]
```
Remember that there will be only 1 `event` *per `programStage`*... meaning that a TEI may have multiple events. Therefore you will need to match on `programStage`...
- If an event with the same `programStage` as the event you want to create already exists --> update this event
- If an event with the same `programStage` as the event you want to import _does NOT_ already exist --> create this incoming event
![Image](https://github.com/user-attachments/assets/283d052b-646f-4229-9fa5-f7d4218f4177)

**Comment by mtuchi** [comment]
Hiya @aleksa-krolls i have mapped the event id so that create event step can update or create events. See this PR #69 
When you want to test just go ahead and merge the PR
