### ISSUE TITLE
Update `fetch-metadata-and-generate-opts-json` workflow to also fetch and append `omrs-forms-metadata` and `identifiers` sheet to the `metadata-json`

### ISSUE THREAD

**Issue by AishaHassen** [OpenFn/openfn-lime-pilot#56]
## Background, context, and business value
New sheet has been added to the metadata file to ensure that we are not hardcoding list of `sheets` to fetch and their corresponding `omrs-form-uuid`, `dhis2-program`, `dhis2-program-stage`. The ask of this issue is to `get` those sheets and add them to the `metadata.json` file being saved on Github.

#### 1. Modify the `Get metadata file from Sharepoint` Job
* First fetch only the `form-metadata` sheet.
* Using that sheet construct a JSON named `state.form-metadata` as shown below:
```
​​[
    {
        "OMRS form name": "F01-MHPSS Baseline",
        "OMRS form.uuid": "6a3e1e0e-dd13-3465-b8f5-ee2d42691fe5",
        "DHIS2 program ID": "w9MSPn5oSqp",
        "DHIS2 programStage ID": "MdTtRixaC1B",
        "OMRS Form Version": "v1"
    },
    {
        "OMRS form name": "F03-mhGAP Baseline",
        "OMRS form.uuid": "82db23a1-4eb1-3f3c-bb65-b7ebfe95b19b",
        "DHIS2 program ID": "w9MSPn5oSqp",
        "DHIS2 programStage ID": "EZJ9FsNau7Q",
        "OMRS Form Version": "v1"
    }]
```
* Loop over the above json array to fetch the sheet for the OMRS forms(F01-MHPSS Baseline, F03-mhGAP Baseline) as opposed to looping a hardcoded list in the job code.
* Instead of putting the output json directly on the `state` object, compile them under `state.form-mappings` so we can dynamically reference them in the subsequent steps. 
* Next fetch a sheet named `identifiers`, construct and JSON array from the table. and save it under `state.identifiers`
* This is what the `state` object should look like after this step:
```
{
  "form-mappings": {
    "f01MhpssBaseline": [],
    "f02MhpssFollowUp": [],
     .....
  },
  "forms-metadata": [],
  "identifiers": [],
  "optionsets": []
}

```

#### 2.  Modify the `Save option-set json to github` step
* In the last step that merges the JSON objects into one large JSON Object, extract the contents of `state.form-mappings` and include `state.form-metadata` into the final JSON Object.

## state.json
{}

## Name of File to fetch from Sharepoing

`LIME EMR - Iraq Metadata - Release 1`

**Comment by aleksa-krolls** [comment]
@mtuchi as discussed on the call: 
1. Let's generate [this formsMap](https://github.com/OpenFn/openfn-lime-pilot/blob/staging/workflows/wf2/4-get-options-map.js#L20C3-L46) in WF3 to add to the collection `metadata.json`
2. Then get [these formuids](https://github.com/OpenFn/openfn-lime-pilot/blob/staging/workflows/wf2/3-get-encounters.js#L1) `wf2/3-get-encounters.js`
3. And then update `wf2/4-get-options-map.js` to get [this formsMap](https://github.com/OpenFn/openfn-lime-pilot/blob/staging/workflows/wf2/4-get-options-map.js#L20C3-L46) from the collection
4.

**Comment by mtuchi** [comment]
**EOD Update** Work in progress #60 

I have manage to complete the mappings and pushing the new generated metadata to `metadata/collection.json` in `next-staging` branch to avoid conflicts on `staging`. And also i have started updating wf2. I need to run the wf2 couple of times to validate my logic for the new mappings before passing the PR to code review. I will continue on this tomorrow

**Comment by mtuchi** [comment]
The implementation for this issue is done, I have handed over the #60 to Joe for code-review

**Comment by aleksa-krolls** [comment]
@mtuchi after wrapping up to NH, pls prioritize implementing code review feedback here

**Comment by mtuchi** [comment]
**EOD Update**  #60 

I have update the mapping in `wf2` and improve the auto generation of `collection.json` in `wf3`. The PR is ready for code review, Once Joe approve i will merge to sync the changes to [msf-lime-test project](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?s=c5c034f3-2488-4a95-944b-1f1d69505dc2&v=1)
cc @aleksa-krolls @AishaHassen
