### ISSUE TITLE
Update WF1 and WF2 to use the `form-metadata` mapping for `program-id, programStage-id, omrs-form-uuid`

### ISSUE THREAD

**Issue by AishaHassen** [OpenFn/openfn-lime-pilot#57]
## Background, context, and business value
Currently `program-id, programStage-id, org-unit-id `are being hardcoded in WF1 and WF2. Instead we can use `form-metadata` in the `metadata.json` file that we have added in issue #56 

## The specific request, in as few words as possible
Modify all job codes that have `program-id, programStage-id, org-unit-id` hardcoded in WF1 and WF2.

**Comment by mtuchi** [comment]
**EOD Update** #56 
WF2 is ready for testing, Pretty much all important mapping are now using the input from the metadata file.  I have started updating mapping for WF1, But lots of jobs are not updated yet. I will pick this up on Monday

**Comment by mtuchi** [comment]
**EOD Update** 

This is ready for code review, See #62
