### ISSUE TITLE
Remove hardcoded DHIS2 codes and data elements in `Upsert-tei's` step in WF2

### ISSUE THREAD

**Issue by AishaHassen** [OpenFn/openfn-lime-pilot#58]
## Background, context, and business value
Currently when upserting TEI's in WF2, we are hardcoding the dhis2 `data element Ids, DHIS2_PATIENT_NUMBER and OPENMRS_AUTO_ID`. The ask of this issue is to replace the hardcoded dhis2 codes with the mapping that we are getting from `metadata.json` file.

## The specific request, in as few words as possible
Update the `Upsert TEI` - [file](https://github.com/OpenFn/openfn-lime-pilot/blob/staging/workflows/wf2/2-upsert-teis.js)
1. 

@aleksa-krolls need your help figuring out which form mapping to use for this

**Comment by aleksa-krolls** [comment]
@AishaHassen I will work on this Monday!

**Comment by aleksa-krolls** [comment]
This was addressed in #57
