### ISSUE TITLE
MSF testing feedback for workflow refactor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#61]
## Issue
I added back console.logs so we can actually see the `events` payload you're sending to the dhis2 api... [here](https://gist.github.com/aleksa-krolls/884a3a525f3ec79f53460e261367aecd) is the latest payload causing errors. 

[See run failure](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?a=a89f0910-b1d7-4d9c-a53a-8276636f07b7&m=expand&s=a1176a6e-cdee-4ddc-9fe1-e49aa7b719cd&v=37) with these errors: 

```
{
  "status": "ERROR",
  "validationReport": {
    "errorReports": [
      {
        "message": "Event: `YKPaC6XbCtE`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "YKPaC6XbCtE"
      },
      {
        "message": "Event: `oI0JAlb7eEv`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "oI0JAlb7eEv"
      },
      {
        "message": "Event: `ScWv14dZJCe`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "ScWv14dZJCe"
      },
      {
        "message": "Event: `kI6rFF9cSBF`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "kI6rFF9cSBF"
      },
      {
        "message": "Event: `I9ogwuEDiP5`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "I9ogwuEDiP5"
      },
      {
        "message": "Event: `NlGWQCzjq0l`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "NlGWQCzjq0l"
      },
      {
        "message": "Event: `FSXFyEC4FlE`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "FSXFyEC4FlE"
      },
      {
        "message": "Event: `GIEwOFq6S5U`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "GIEwOFq6S5U"
      },
      {
        "message": "Event: `fvElC0XZTFc`, Enrollment value is null.",
        "errorCode": "E1033",
        "trackerType": "EVENT",
        "uid": "fvElC0XZTFc"
      },
      {
        "message": "DataElement `iEdamWl0wzQ` is not valid: `value_not_zero_or_positive_integer`",
        "errorCode": "E1302",
        "trackerType": "EVENT",
        "uid": "hDMY0TQezaD"
      },
      {
        "message": "Value cgi-s_score|0 is not a valid option for iEdamWl0wzQ DataElement in option set 1,2,3,4,5,6,7",
        "errorCode": "E1125",
        "trackerType": "EVENT",
        "uid": "hDMY0TQezaD"
      },
      {
        "message": "DataElement `c4TiPRUQ56A` is not valid: `value_not_zero_or_positive_integer`",
        "errorCode": "E1302",
        "trackerType": "EVENT",
        "uid": "hDMY0TQezaD"
      },
      {
        "message": "Value cgi-s_score|0 is not a valid option for c4TiPRUQ56A DataElement in option set 1,2,3,4,5,6,7",
        "errorCode": "E1125",
        "trackerType": "EVENT",
        "uid": "hDMY0TQezaD"
      },
      {
        "message": "Value 2 is not a valid option for tsFOVnlc6lz DataElement in option set 0_4,5_9,10_14,15_19,>20",
        "errorCode": "E1125",
        "trackerType": "EVENT",
        "uid": "hDMY0TQezaD"
      }
    ]
```

## My Errors Analysis
There are 4 issues here: 
1. For the error `Enrollment value is null`, only 1 of these events is linked to a TEI or enrollment (see [L222](https://gist.github.com/aleksa-krolls/884a3a525f3ec79f53460e261367aecd#file-dhis2events_import_failed-json-L222)). I think this means something is wrong in the `Upsert TEI` step or the mappings. **The other events are _not_ linked to a `trackedEntity` at all! 
- [See my comment on #34](https://github.com/OpenFn/openfn-lime-pilot/issues/34#issuecomment-2466810097)** with guidance on how to solve this. 
- We expect each TEI to have 1 `enrollment` in the program `w9MSPn5oSqp`, and if not - we enroll them in step [wf2/2-upsert-teis.js](https://github.com/OpenFn/openfn-lime-pilot/blob/next-staging/workflows/wf2/2-upsert-teis.js#L93-L96). 
- Each `enrollment` has an id, which we should include in this events mapping like this: 
```
{
    "program": "w9MSPn5oSqp",
    "orgUnit": "OPjuJMZFLop",
    "trackedEntity": "gVukOXy6qks",
    "enrollment": "BCVoZgbAFLu", //should include and get from earlier step
    "occurredAt": "2024-11-08T16:52:49.000",
    "programStage": "xrCTheIzyDV",
    "dataValues": [ ... ] 
}
```
2. Error `"message": "Value 2 is not a valid option for tsFOVnlc6lz DataElement in option set 0_4,5_9,10_14,15_19,>20",`
- On [L252](https://gist.github.com/aleksa-krolls/884a3a525f3ec79f53460e261367aecd#file-dhis2events_import_failed-json-L251-L252) we're sending the value `2` instead of `0_4`... why? We should send `0_4` as per the [getRangePhq](https://github.com/OpenFn/openfn-lime-pilot/blob/next-staging/workflows/wf2/6-create-events.js#L54-L60) custom transformation. 

3. For the errors related to `Data Element c4TiPRUQ56A`
- On [L240](https://gist.github.com/aleksa-krolls/884a3a525f3ec79f53460e261367aecd#file-dhis2events_import_failed-json-L239-L240) looks like we were sending `cgi-s_score|0`. 
- There was an issue with the optionSet mapping that I'm flagging to the client. 
- In the meantime, I've updated the [optionSet](https://openfnorg.sharepoint.com/:x:/r/sites/openfn-msf-test/_layouts/15/Doc.aspx?sourcedoc=%7B0FCD6FD8-9541-4CF6-850A-958B37C4044E%7D&file=LIME%20EMR%20-%20Iraq%20Metadata%20-%20Release%201.xlsx&action=default&mobileredirect=true) sheet... can you please regenerate the collection and lmk if this resolves the issue or if it's still outstanding? 

4. For the errors related to `Data Element iEdamWl0wzQ`
- On [L244](https://gist.github.com/aleksa-krolls/884a3a525f3ec79f53460e261367aecd#file-dhis2events_import_failed-json-L243-L244) looks like we're sending `cgi-s_score|0`
- In the meantime, I've updated the [optionSet](https://openfnorg.sharepoint.com/:x:/r/sites/openfn-msf-test/_layouts/15/Doc.aspx?sourcedoc=%7B0FCD6FD8-9541-4CF6-850A-958B37C4044E%7D&file=LIME%20EMR%20-%20Iraq%20Metadata%20-%20Release%201.xlsx&action=default&mobileredirect=true) sheet... can you please regenerate the collection and lmk if this resolves the issue or if it's still outstanding?

**Comment by mtuchi** [comment]
@aleksa-krolls any update here ?

**Comment by daissatou2** [comment]
@mtuchi the `Create Events` step is failing, see [run](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?a=523b2575-5a94-4335-9455-5623aaa74011&m=expand&s=ecaf53cc-fbde-4703-827b-7b8a5126fb82&v=30#log). I was attempting to sync a new `MSF Mental Health - mhGAP Closure` submission for the patient with `MSF ID:
IQ146-24-000-742`.

**Comment by aleksa-krolls** [comment]
hey @mtuchi I've updated this issue description with my issues of the errors thrown in recent run failures. Please address these and then hand back to Aicha for testing. 

@daissatou2 please see [this video](https://www.loom.com/share/2b96548669e24ef1a142295048ae739c?sid=e6c850c1-6b8f-417c-832d-b625852501a2) for guidance on how to troubleshoot and record any other errors like these going forward. Thanks!

**Comment by mtuchi** [comment]
**EOD Update**

- Added a condition that filter patient without `trackedEntity` and `enrollment` and logged the patient id
- Logged the `encountersMapping` payload on `create events` step. 
- Convert matching option with the value of `no` to `FALSE` and `yes` to `TRUE`

[Test the latest changes here](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?v=47)

**Comment by aleksa-krolls** [comment]
@mtuchi good news is that I was able to resolve most of the `event` errors! Will walk you through it tomorrow. 

But now the wf is failing on `next-staging` when trying to update the TEI's `gender` in the last step. [See run failure](https://app.openfn.org/projects/69066751-5f2c-459c-b42e-feba1c802383/w/c886121c-0a91-45b5-ae30-7d0922b693be?s=abe0d282-5209-47b5-9272-4cba048a5ba8&v=78&m=expand&a=2fa09028-37b1-4535-8c53-2562b8ecf9aa#log) and error. 

```
Failed step Update TEIs after 202ms
{
  "message": "TypeError: Cannot destructure property 'trackedEntity' of 'TEIs[answer.person.uuid]' as it is undefined.",
  "name": "RuntimeError",
  "severity": "fail",
  "source": "runtime",
  "subtype": "TypeError"
}
```

**Comment by mtuchi** [comment]
Hey @aleksa-krolls i have filtered person without `trackedEntity` in `update-teis` step and add a log of the person uuid.  The changes are already synced to app you can proceed with testing
