### ISSUE TITLE
collections mappings updates for `Place of living` and patient `sex`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime-pilot#70]
## Background, context, and business value

This builds on #56 and #53 

## The specific request, in as few words as possible

**(1)** First, can you please update `wf2`  to dynamically get `genderOptions` from the [OptionSets sheet](https://openfnorg.sharepoint.com/:x:/s/openfn-msf-test/EdhvzQ9BlfZMhQqVizfEBE4B4c7sA9QYRrU02Wa2RsF4nw?e=HfUAf7&nav=MTJfQjI2NTdfezczQUQ3NDA0LUVDMjMtNENBQS1CQzkzLTMxQ0JCRTNBNzVDOX0) where 
```
state.genderOptions = state.optsMap
    .filter(o => o['OptionSet name'] === 'state.genderOptions')
```
The current implementation hard codes these mappings: 
https://github.com/OpenFn/openfn-lime-pilot/blob/next-staging/workflows/wf2/2-mappings.js#L54-L59

**(2)** Then, the client wants to maintain a separate sheet for [Place of living](https://openfnorg.sharepoint.com/:x:/r/sites/openfn-msf-test/_layouts/15/doc2.aspx?sourcedoc=%7B0FCD6FD8-9541-4CF6-850A-958B37C4044E%7D&file=LIME%20EMR%20-%20Iraq%20Metadata%20-%20Release%201.xlsx&action=default&mobileredirect=true) options because there are _so_ many and it's making the OptionSets sheet too long/hard to manage. Therefore can you please: 
1. Update `wf3` to save `placeOfLivingMap` as a separate object in the `metadata/collection.json`
2. Update `wf2` so that `state.placeOflivingMap = state.placeOfLivingMap` (instead of `state.optsMap`)

See current implementation: https://github.com/OpenFn/openfn-lime-pilot/blob/next-staging/workflows/wf2/2-mappings.js#L61-L66

**Please branch off of `next-staging` before making edits.**

## Toggl 
`MSF 2024`

**Comment by mtuchi** [comment]
**EOD Update**

Hiya @aleksa-krolls i have implemented the changes for this issue, See #71
